service: gallery
frameworkVersion: '2'

plugins:
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

 #############################################################
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-2'}

  environment:
    GALLERY_TABLE: gallery-${self:provider.stage}
    MEDIA_S3_BUCKET: gallery-${self:provider.stage}-866937819247
    SIGNED_URL_AGE: 300

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.GALLERY_TABLE}
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: 'arn:aws:s3:::${self:provider.environment.MEDIA_S3_BUCKET}/*'

#############################################################################
custom:
  documentation:
    api:
      info:
        version: v1.0.0
        title: gallery api
        description: simple gallery app
    models:
      - name: galleryRequest
        contentType: application/json
        schema: ${file(models/create-gallery-request.json)}

#############################################################################
functions:
  getGallery: 
    handler: src/lambda/http/getGallery.handler
    events:
      - http:
          method: get
          path: gallery
          cors: true

  createGallery: 
    handler: src/lambda/http/createGallery.handler
    events:
      - http:
          method: post
          path: gallery
          cors: true
          reqValidatorName: RequestValidator
          documentation:
            summary: create new gallery 
            description: create new gallery
            requestModels:
              'application/json': galleryRequest

##########################################################
resources:
  Resources:

    RequestValidator:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'request-body-validator'
        RestApiId: 
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true
        ValidateRequestParameters: false

    GalleryDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.GALLERY_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    
    galleryBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.MEDIA_S3_BUCKET}
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - GET
                - POST
                - DELETE
                - PUT
                - HEAD
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              MaxAge: ${self:provider.environment.SIGNED_URL_AGE}

    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref galleryBucket
        PolicyDocument:
            Id: galleryBucketPolicy
            Statement:
              - Sid: PublicReadForGetBucketObjects
                Effect: Allow
                Principal: '*'
                Action: 's3:GetObject'
                Resource: 'arn:aws:s3:::${self:provider.environment.MEDIA_S3_BUCKET}/*'